app: day1-historian-hysteria.o merge-sort.o
	gcc -o app day1-historian-hysteria.o merge-sort.o

day1-historian-hysteria.o: day1-historian-hysteria.c merge-sort.h
	gcc -c day1-historian-hysteria.c

merge-sort.o: merge-sort.c merge-sort.h
	gcc -c merge-sort.c