clever: day6-guard-gallivant.o
	gcc -o clever day6-guard-gallivant.o

day6-guard-gallivant.o: day6-guard-gallivant.c
	gcc -c day6-guard-gallivant.c

bruteforce: day6-guard-gallivant-brute-force.o
	gcc -o bruteforce day6-guard-gallivant-brute-force.o

day6-guard-gallivant-brute-force.o: day6-guard-gallivant-brute-force.c
	gcc -c day6-guard-gallivant-brute-force.c