app: day23-LAN-party.o
	gcc -o app day23-LAN-party.o

day23-LAN-party.o: day23-LAN-party.c
	gcc -c day23-LAN-party.c

pt2: day23-LAN-party-part2.o
	gcc -o pt2 day23-LAN-party-part2.o

day23-LAN-party-part2.o: day23-LAN-party-part2.c
	gcc -c day23-LAN-party-part2.c