app: day9-disk-fragmenter.o
	gcc -o app day9-disk-fragmenter.o

day9-disk-fragmenter.o: day9-disk-fragmenter.c
	gcc -c day9-disk-fragmenter.c

printer: print-disk-state.o
	gcc -o printer print-disk-state.o

print-disk-state.o: print-disk-state.c
	gcc -c print-disk-state.c

counter: calculate-total.o
	gcc -o counter calculate-total.o

calculate-total.o: calculate-total.c
	gcc -c calculate-total.c